FROM python:3.12-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    i2c-tools \
    gcc \
    build-essential \
    linux-headers-generic

# Set working directory
WORKDIR /app

# Copy application code
COPY src/gpio/ .
COPY src/common/ ./common/

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the application
CMD ["python", "api.py"]
